spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-application
          uri: lb://CUSTOMER-APPLICATION
          predicates:
            - Path=/api/v1/customer/**
        - id: fraud-check-application
          uri: lb://FRAUD-CHECK-APPLICATION
          predicates:
            - Path=/api/v1/fraud-check/**
        - id: notification-application
          uri: lb://NOTIFICATION-APPLICATION
          predicates:
            - Path=/api/v1/notification/**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



server:
  port: 9000